[project]
name = "mlflow-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "load-dotenv>=0.1.0",
    "mlflow>=3.3.2",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.7.1",
]
